class Git < Scm
  
  def initialize_repository
    #git init
    add_origin
  end
  
  # delete files we don't ever want, ignore some others
  def remove_unwanted_files
    # git rm public/index.html public/images/rails.png
    ignore_files
    populate_empty_directories
  end
  
  def install_plugins
    @site.selected_plugins.each do |p|
      # git submodule add p.plugin.remote_url p.plugin.local_path
      
      if p.plugin.generator_call_required?
        # p.generator_call
      end
    end
  end
  
  def track_all_files
    # git add .
  end
  
  def push_to_server
    # git push origin master
  end
  
  
  private
  
  def add_origin
    # git remote add origin 
  end
  
  def commit
    # git commit -m "Application Generated by Rails App Generator"
  end
  
  # set up .gitignore file
  def ignore_files
    
  end
  
  #adds a .gitignore file to any empty directories - ensures that git will track those dirs
  def populate_empty_directories
    
  end
end