class Git < Scm
  
  def initialize_repository
    system("cd #{to_dir} && git init")
    add_origin
  end
  
  def install_plugins
    @site.selected_plugins.each do |p|
      system("cd #{to_dir} && git submodule add #{p.plugin.remote_url} #{p.plugin.local_path}")
      
      if p.plugin.generator_call_required?
        # TODO: p.generator_call
      end
    end
  end
  
  def track_all_files
    ignore_files
    populate_empty_directories
    system("cd #{to_dir} && git add .")
    commit
  end
  
  def push_to_server
    # git push origin master
  end
  
  
  private
  
  def add_origin
    # git remote add origin 
  end
  
  # commits all files to the repo with a default message
  def commit
    system("cd #{to_dir} && git commit -m \"Application Generated by Rails App Generator\"")
  end
  
  # set up .gitignore file
  def ignore_files
    system("cp .gitignore #{to_dir}/.gitignore")
  end
  
  #adds a .gitignore file to any empty directories - ensures that git will track those dirs
  def populate_empty_directories
    system("cd #{to_dir} && find . \( -type d -empty \) -and \( -not -regex ./\.git.* \) -exec touch {}/.gitignore \;")
  end
  
  def to_dir
    "../#{@site.underscored_name}"
  end
end